2022-03-08 14:01:59,727 (36522/MainThread) litecli.main ERROR - sql: 'create database main;', error: OperationalError('near "database": syntax error')
2022-03-08 14:01:59,728 (36522/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/usr/lib/python3.10/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/litecli/main.py", line 442, in one_iteration\n    for title, cur, headers, status in res:\n  File "/usr/lib/python3.10/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "database": syntax error\n'
2022-03-08 14:02:05,973 (36522/MainThread) litecli.main ERROR - sql: 'create database teste', error: OperationalError('near "database": syntax error')
2022-03-08 14:02:05,973 (36522/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/usr/lib/python3.10/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/litecli/main.py", line 442, in one_iteration\n    for title, cur, headers, status in res:\n  File "/usr/lib/python3.10/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "database": syntax error\n'
